### PR TITLE
Update mdbook and other dependencies.

### PR DESCRIPTION
**Pull request by sapir**

### CODE REVIEW

**Comment by sapir** [comment]
Current version fails with an IncompatibleMdbookVersion for current mdbook (0.2.1). So [this PR I opened for rustwasm-book](https://github.com/rustwasm/book/pull/97) is broken; the rustwasm-book build is using mdbook 0.2.

If I update the dependencies, then the output looks ok to me.

**Comment by sapir** [comment]
ok

**Comment by blandger** [comment]
PR looks ok for me, but needs conflict resolving.
I don't see much problems for resolving in Cargo.toml, tests/integration_tests.rs
but resolution in Cargo.lock needs the local file regeneration it's it (or taking all from PR's branch )?

**Comment by Michael-F-Bryan** [comment]
@blandger it's probably easier to start again from scratch. This PR upgrades from `0.1.0` to `0.2.1` and mdbook is currently around `0.4.4`.

**Comment by blandger** [comment]
> @blandger it's probably easier/cleaner to start again from scratch. This PR upgrades from `0.1.0` to `0.2.1` and mdbook is currently around `0.4.4`.

If you talk about upgrade to 0.4.4 and moving proposed changes in another, fresher PR... yes, I think that is quite feasible. I will create new PR for that set of changes.

**Comment by blandger** [comment]
That PR ca be closed, as all those changes are in latest code. So no sense to keep it.

**Comment by blandger** [comment]
close that as out dated

**Pull request closed without merging**
