### PR TITLE
Upgrading to mdbook@0.4.x.

### PR DESCRIPTION
**Pull request by tmpfs**
* Use `as_ref().unwrap()` for chapter paths that are now Option.
* Migrate to `thiserror` and remove `failure`.
* Remove obsolete utils.rs.

Needed to add the toml dependency for error conversion.

### CODE REVIEW

**Comment by Michael-F-Bryan** [comment]
@tmpfs, do you know why the Windows build is failing?

**Comment by tmpfs** [comment]
Nope, sorry I compiled and ran it all on Linux and have a Macos box to test on if needs be. My guess would be to do with one of the dependencies; Windows is not my strong point. But looking at the output it seems pretty clear the error, I just don't know *why* the file is not found:

```
---- look_for_chapter_1_heading stdout ----
thread 'look_for_chapter_1_heading' panicked at 'called `Result::unwrap()` on an `Err` value: FileNotFound', tests\integration_tests.rs:76:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
---- rendered_document_contains_all_chapter_files_and_assets stdout ----
thread 'rendered_document_contains_all_chapter_files_and_assets' panicked at 'OEBPS\chapter_1.html', tests\integration_tests.rs:91:9
```

**Comment by tmpfs** [comment]
My guess would be `epub::doc::EpubDoc` is not working correctly on Windows.

**Comment by tmpfs** [comment]
Trawling through the lock file to see what versions changed I noticed that I can switch off `default-features` for mdbook so that there is no `warp`, `hyper` dependencies etc pulled down by mdbook. I don't think we need them.

This won't fix the Windows problem though!

**Comment by Michael-F-Bryan** [comment]
Could it be related to #11? If so, it's not related to your PR and we could always disable the offending test on Windows (`#[cfg_if(windows, ignore)]`) as a workaround.

**Comment by blandger** [comment]
As I can see that PR is most actual for upgrading code to latest library versions. It fixes several issues with new Libraries. I will examine it more thoroughly while trying to upgrade code locally.

**Comment by blandger** [comment]
@Michael-F-Bryan I bumped up all libraries to latest versions and fixed errors for initial code (no PR yet).
What do you think about switching to **thiserror** proposed by @tmpfs ? I didn't put that in my changes and left failure = "0.1.3" for now. We can switch to thiserror on next PR or stay with **failure**. That doesn't matter for me personally.

Currently code fails on processing book assets. That is the same error I had before, but all libs are upgraded at least and I can create PR.

```
$ RUST_BACKTRACE=1 ./mdbook-epub -s .
[2020-10-22T18:01:25Z ERROR mdbook_epub] Inspecting the book for additional assets failed
	Caused By: Unable to fetch the canonical path for /media/ylarin/PHOTO/rust_projects/rust-book-ru-blangder/rustbook-ru/src/https://github.com/ruRust/book/blob/master/rustbook-en/src/img/trpl20-01.png?raw=true
```

**Comment by blandger** [comment]
My local commit : https://github.com/blandger/mdbook-epub/commit/ffe924a560de2f0b682c716528747e331cd80f0d

**Comment by Michael-F-Bryan** [comment]
For error handling I'd remove `failure` and use either `anyhow` or `thiserror` with custom error types.

Generally I'll prefer `anyhow` in executables because you get nice things like backtraces and often you don't care *what* the error was, just that there was an error and it should be propagated up. Using `anyhow::Error` means you've got a single error type that everything can be converted to.

**Pull request closed without merging**
