### PR TITLE
ci: add Github workflows

### PR DESCRIPTION
**Pull request by dieterplex**
Based on starship's workflows to run cargo fmt, clippy, check

### CODE REVIEW

**Comment by blandger** [comment]
Why do you think we need that ? Travis CI works quite fine....

**Comment by dieterplex** [comment]
Rationale see #71.

This PR is testing cross platform, cargo format and clipply not provided by AppVeyor and used in my fork for a while.
Do you prefer add these functionality to AppVeyor? What I know is AppVeyor is working when testing PR. Is Travis CI really working here?

**Comment by blandger** [comment]
May be we can use shorter YAML version ?

`
name: Rust

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Rust
      uses: actions/checkout@v2
    - name: Install cargo version
      uses: dtolnay/rust-toolchain@stable
    - name: Install cargo audit
      run: cargo install cargo-audit
    - name: Install btleplug libraries
      run: sudo apt install libdbus-1-dev pkg-config
    - name: Show rust version
      run: cargo --version
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run Clippy
      run: cargo clippy -- -Dwarnings
`

Last steps like Run Clippy can be turned off for now, because we have issue probably.

**Comment by blandger** [comment]
Added simplest GH action script.

**Pull request closed without merging**
