### PR TITLE
Feature/replace error library

### PR DESCRIPTION
**Pull request by blandger**
- error library is replaced by thiserror with help of changes from PR #35 by @tmpfs 
- added more logging in generator.rs while I was investigating error of generation rust-book-ru version

Content had a link to external url 
`hello from rust`
instead of 
`hello from rust`

so epub processing failed with unclear error :
Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/generator.rs:157:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

so I added a little tip into it
thread 'main' panicked at 'Failed finding/fetch resource taken from content? Look up content for possible error...: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/generator.rs:157:48

### CODE REVIEW

**Comment by blandger** [comment]
There are other problems like images are not included into epub as assets/recources

изображение

**Comment by blandger** [comment]
I tried to add image resources into book.toml for rust-book processing. There are several images which are referred from content.

additional-resources = ["src/img/ferris/does_not_compile.svg",........,"src/img/trpl20-01.png"]
Image like: hello from rust
is processed and added into final epub container.
The other images referred in content as : 
is not composed included into epub container although it's processed according to logs.

As I can see **pulldown_cmark** is not able to process/parse such html image/links (if I'm not mistaken). Do we need another additional parser for such case probably? Or... probably those images might be included into epub container as assets ?

**Comment by blandger** [comment]
I've managed to build correct EPUB version of "rust book" by using changes in commit `fixed correct adding images into epub`. Now images added to config:
```
.........
[output.epub]
cover-image = "img/book_cover.jpg"
additional-resources = ["img/ferris/does_not_compile.svg".... ,"img/trpl15-03.svg","img/trpl15-04.svg","img/trpl20-01.png"]
```
are packaged into epub folder and images are rendered inside the book correctly.

Overall book view is still ugly a bit, but built quite correctly with all necessary stuff inside (package.opf, toc.ncx, toc.xhtml, nav.xhtml generated for free by epub-builder)

The linked source code is still a problem.
`{{#rustdoc_include ../listings/ch14-more-about-cargo/listing-14-01/src/lib.rs}}`

@Michael-F-Bryan do you have ideas how to manage that stuff properly??? I thought about extending pulldown-cmark some how... but I don't see some kind of 'custom tags or custom hooks' to process such content there.

**Comment by Michael-F-Bryan** [comment]
> As I can see pulldown_cmark is not able to process/parse such html image/links (if I'm not mistaken). Do we need another additional parser for such case probably? Or... probably those images might be included into epub container as assets ?

If you want to handle `` tags you'll need to rewrite the [`pulldown_cmark::Event::Html`](https://docs.rs/pulldown-cmark/0.8.0/pulldown_cmark/enum.Event.html#variant.Html) event to a emit the `Event::Start` and `Event::End` for a [`Tag::Image`](https://docs.rs/pulldown-cmark/0.8.0/pulldown_cmark/enum.Tag.html#variant.Image).

I made the [`markedit`](https://docs.rs/markedit) crate for doing this sort of event rewriting. You can also see [the blog post](https://adventures.michaelfbryan.com/posts/markedit/#making-a-rewriter) to get an idea of how it's meant to be used and the thought process behind the design.

> The linked source code is still a problem.
>
> `{{#rustdoc_include ../listings/ch14-more-about-cargo/listing-14-01/src/lib.rs}}`

How are you running `mdbook-epub`? The `rustdoc_include` should have been handled by the corresponding preprocessor before it was given to `mdbook-epub` for rendering.

These preprocessors will replace `{{#rustdoc_include ...}}` and friends with the corresponding file's contents, so `mdbook-epub` shouldn't even know it exists.

> Now images are added to config:
> ```toml
> [output.epub]
> cover-image = "img/book_cover.jpg"
> additional-resources = ["img/ferris/does_not_compile.svg".... ,"img/trpl15-03.svg","img/trpl15-04.svg","img/trpl20-01.png"]
> ```

That sounds like a pain to maintain. A better solution would be for a `mdbook::Book` to contain all the resources that should go into a book and not just the markdown chapters, then you don't need to work around it with a `additional-resources` section. I believe The HTML renderer works around this issue by blindly copying all non-markdown files from `src/` to the output directory.

Maybe https://github.com/rust-lang/mdBook/pull/1341 could help here?

**Comment by blandger** [comment]
**The issue 1.**

> If you want to handle `` tags you'll need to rewrite the [`pulldown_cmark::Event::Html`](https://docs.rs/pulldown-cmark/0.8.0/pulldown_cmark/enum.Event.html#variant.Html) event to a emit the `Event::Start` and `Event::End` for a [`Tag::Image`](https://docs.rs/pulldown-cmark/0.8.0/pulldown_cmark/enum.Tag.html#variant.Image).

That was my first idea and I tried that way a little. But I realized that parsing HTML content will take time. So I decided take short path. I would better to postpone the HTML event processing and content parsing. I've found it is quicker to add those image HTML files as resources. I added more code to find/locate those resources in different places, so now it works better.

> I made the [`markedit`](https://docs.rs/markedit) crate for doing this sort of event rewriting. You can also see [the blog post](https://adventures.michaelfbryan.com/posts/markedit/#making-a-rewriter) to get an idea of how it's meant to be used and the thought process behind the design.

I propose postpone that for later. Now I would like to fix epub creation at the first place.



> How are you running `mdbook-epub`? The `rustdoc_include` should have been handled by the corresponding preprocessor before it was given to `mdbook-epub` for rendering.

I don't see that preprocessing.  Usually I run it like:
`$ ./mdbook-epub/target/debug/mdbook-epub -s /full_path_to/rust-book/rustbook-ru`

Now EPUB book is built successfully with all those latest changes from two PRs, but 1) CSS needs improvements for gaps, image alignment/size is ugly too, 2) `{{#rustdoc_include ...}}` are not processed.



> > Now images are added to config:
> > ```toml
> > [output.epub]
> > additional-resources = ["img/ferris/does_not_compile.svg","img/trpl15-03.svg","img/trpl15-04.svg","img/trpl20-01.png"]
> > ```

> That sounds like a pain to maintain. A better solution would be for a `mdbook::Book` to contain all the resources that should go into a book and not just the markdown chapters, then you don't need to work around it with a `additional-resources` section. I believe The HTML renderer works around this issue by blindly copying all non-markdown files from `src/` to the output directory.

In general you are right, but that way works as workaround now, so I think its lower priority.

> Maybe [rust-lang/mdBook#1341](https://github.com/rust-lang/mdBook/pull/1341) could help here?

Yes, I will look that later.


**The issue 2.**

> These preprocessors will replace `{{#rustdoc_include ...}}` and friends with the corresponding file's contents, so `mdbook-epub` shouldn't even know it exists.

I looked at 'links preprocessor' inside 'mdbook' sources.
https://github.com/rust-lang/mdBook/blob/master/src/preprocess/links.rs#L54

They call those TOML registered preprocessors for the whole book on sources calling trait method and internal implementation (replace_all() method). The registered preprocessors are called like a chain for all book sources. 
https://github.com/rust-lang/mdBook/blob/master/src/preprocess/mod.rs#L54
`    fn run(&self, ctx: &PreprocessorContext, book: Book) -> Result<Book>;`

But in 'mdbook-epub' we are processing files/sources 'one-by-one' taking from src/ folder. So I decided to : 1. reuse mdbook preprocessors functionality to call that for one processed Chapter within 'epub'.

I was able to do following changes on my local fork:
1. update `pub trait Preprocessor {` by adding new method for 'one Chaper' processing.
`fn preprocess_chapter(&self, ctx: &PreprocessorContext, chapter: &mut Chapter) -> Result<()> {`

2. make that trait clonable, so I can clone preprocessors and provide them for epub generation code.
mdbook changes - https://github.com/rust-lang/mdBook/compare/master...blandger:master

3. Now I have branch (not pushed) with changes where 'links preprocessor' is used and called to modify chapter's content inside 
```
fn add_chapter(&mut self, ch: ......) -> ... {
       for renderer in &self.preprocessors {
           renderer.preprocess_chapter(&self.preprocess_ctx, &ch)?;
       }
       let rendered = self.render_chapter(&ch)?;
```
before Chapter rendering.
But there is a problem with resource lookup again. The 'link for file' pointing to target (../listings/ch02-guessing-game-tutorial/..)  is not found inside mdBook proprocessor's code. I checked by running modified test 
**integration_tests.rs**
**#[test] fn look_for_chapter_1_heading()**
The preprocessor code doesn't find target file for link replacement now. WIP.

**Comment by blandger** [comment]
Here are two built epub TRPL books I've created locally for English and Russian languages.
https://github.com/rust-lang-ru/book/releases/tag/0.0.1-alpha

**Comment by blandger** [comment]
Are there objections for merge ?

**Comment by blandger** [comment]
If no objections, I'll merge...

**Pull request merged**
